### ISSUE TITLE
Error after composer dependency update

### ISSUE THREAD

**Issue by jamesblackwell** [PhiloNL/Laravel-Twitter#8]
After the dependency update in composer.json I'm getting this error: 

```
Call to private method TijsVerkoyen\Twitter\Twitter::setConsumerKey() from context 'Philo\Twitter\Twitter'
```

I forked and reversed and it resolved the situation. Just intrigued as to why this was updated? Especially after no changes for a long time.

**Comment by PhiloNL** [comment]
Sorry about that. I've changed the dependency back to master.
There were some issue's getting this package installed when minimum-stability is set to stable.
But noticed the stable release of TijsVerkoyen\Twitter is actually out of date.
Let me know if the issue is now resolved.

**Comment by jamesblackwell** [comment]
Thanks, it's all sorted now :)
